apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: rag-p1742388741390
  janus-idp.io/tekton: rag-p1742388741390
  backstage.io/kubernetes-id: rag-p1742388741390
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: rag-p1742388741390
resources:
  - application-dev.yaml
