apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: rag-p1742388741390
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rag-p1742388741390
  name: rag-p1742388741390
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
