apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: rag-p1742388741390
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rag-p1742388741390
  name: rag-p1742388741390
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: rag-p1742388741390
    weight: 100
  wildcardPolicy: None
