apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: rag-p1742388741390
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rag-p1742388741390
  name: rag-p1742388741390
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: rag-p1742388741390
